In [2]:
# NumPy Basics

In [5]:
import numpy as np

my_arr = np.arange(1000000)

my_list = list(range(1000000))

In [8]:
%time for _ in range(10) : my_arr2 = my_arr * 2

Wall time: 21 ms


In [9]:
%time for _ in range(10) : my_list2 = [ x * 2 for x in my_list]

Wall time: 763 ms


In [10]:
import numpy as np

# Generate some random data
data = np.random.randn( 2, 3 )

data

array([[-1.48307301, -0.99154354, -0.61717105],
       [ 0.28804592, -0.04461058,  0.98205062]])

In [11]:
data * 10

array([[-14.83073007,  -9.91543545,  -6.17171053],
       [  2.88045922,  -0.44610575,   9.82050619]])

In [12]:
data + data

array([[-2.96614601, -1.98308709, -1.23434211],
       [ 0.57609184, -0.08922115,  1.96410124]])

In [13]:
data.shape

(2, 3)

In [14]:
data.dtype

dtype('float64')

In [15]:
data1 = [ 6, 7.5, 8, 0, 1]

In [16]:
arr1 = np.array(data1)

In [17]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [19]:
data2 = [[1,2,3,4], [5,6,7,8]]

In [20]:
arr2 = np.array(data2)

In [21]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
arr2.ndim

2

In [23]:
arr2.shape

(2, 4)

In [24]:
arr1.dtype

dtype('float64')

In [25]:
arr2.dtype

dtype('int32')

In [26]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [27]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [28]:
np.empty((2,3,2))

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [29]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
arr1 = np.array( [1,2,3], dtype = np.float64)

In [31]:
arr1.dtype

dtype('float64')

In [32]:
arr2 = np.array([1,2,3], np.int32)

In [33]:
arr2.dtype

dtype('int32')

In [34]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [35]:
float_arr = arr.astype( np.float64 )

In [36]:
float_arr.dtype

dtype('float64')

In [37]:
arr = np.array( [3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [38]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [39]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype = np.string_)

In [40]:
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [42]:
int_array = np.arange(10)

calibers = np.array([.22, .270, .357, .44, .50], dtype = np.float64)

int_array.astype( calibers.dtype )

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [43]:
empty_uint32 = np.empty(8, dtype = 'u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [45]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [46]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [47]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [48]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [49]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [50]:
arr2 = np.array( [[0., 4., 1.], [7., 2., 12]])
arr2

array([[  0.,   4.,   1.],
       [  7.,   2.,  12.]])

In [51]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]], dtype=bool)

In [52]:
arr = np.arange(10)

In [53]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr[5]

5

In [55]:
arr[5:8]

array([5, 6, 7])

In [56]:
arr[5:8] = 12

In [57]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [58]:
arr_slice = arr[5:8]

In [59]:
arr_slice

array([12, 12, 12])

In [60]:
arr_slice[1] = 12345

In [61]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [62]:
arr_slice[:] = 64

In [63]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [71]:
arr2 = arr[5:8].copy()
arr2[:] = .5

In [72]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [73]:
arr2

array([0, 0, 0])

In [74]:
arr2d = np.array( [[1,2,3], [4,5,6], [7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
arr2d[2]

array([7, 8, 9])

In [77]:
arr2d[0][2]

3

In [78]:
arr2d[0,2]

3

In [81]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10, 11, 12]]])

In [82]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [83]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
old_values = arr3d[0].copy()

In [85]:
arr3d[0] = 42

In [86]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [87]:
arr3d[0] = old_values

In [88]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [90]:
arr3d[ 1, 0 ]

array([7, 8, 9])

In [91]:
x = arr3d[1]
x[0]

array([7, 8, 9])

In [92]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [93]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [94]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
arr2d[1, :2]

array([4, 5])

In [97]:
arr2d[:2, 2]

array([3, 6])

In [99]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [100]:
arr2d[:2, 1:] = 0

In [101]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [102]:
names = np.array( ['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)

In [103]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='<U4')

In [104]:
data

array([[-0.74430497,  1.39722234, -0.76299323,  0.97079403],
       [-1.39498013,  0.54200134, -0.33098969,  0.70987597],
       [ 0.58468217, -0.51504308, -0.39459975, -0.51286973],
       [-0.13113865,  0.23601472,  0.389689  , -0.75906031],
       [-0.18852461,  0.5815627 , -1.12602844,  0.11855117],
       [ 0.18384131, -0.8386468 , -0.06625112, -1.63735578],
       [ 0.2793218 ,  1.30167366, -1.15097801,  0.19195833]])

In [105]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [106]:
data[names == 'Bob']

array([[-0.74430497,  1.39722234, -0.76299323,  0.97079403],
       [-0.13113865,  0.23601472,  0.389689  , -0.75906031]])

In [107]:
data[names == 'Bob', 2:]

array([[-0.76299323,  0.97079403],
       [ 0.389689  , -0.75906031]])

In [108]:
data[names == 'Bob', 3]

array([ 0.97079403, -0.75906031])

In [109]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [110]:
data[~(names == 'Bob')]

array([[-1.39498013,  0.54200134, -0.33098969,  0.70987597],
       [ 0.58468217, -0.51504308, -0.39459975, -0.51286973],
       [-0.18852461,  0.5815627 , -1.12602844,  0.11855117],
       [ 0.18384131, -0.8386468 , -0.06625112, -1.63735578],
       [ 0.2793218 ,  1.30167366, -1.15097801,  0.19195833]])

In [112]:
cond = names == 'Bob'

In [113]:
data[~cond]

array([[-1.39498013,  0.54200134, -0.33098969,  0.70987597],
       [ 0.58468217, -0.51504308, -0.39459975, -0.51286973],
       [-0.18852461,  0.5815627 , -1.12602844,  0.11855117],
       [ 0.18384131, -0.8386468 , -0.06625112, -1.63735578],
       [ 0.2793218 ,  1.30167366, -1.15097801,  0.19195833]])

In [115]:
mask = ( names == 'Bob') | (names == 'Will')

In [118]:
data[mask]

array([[ 0.        ,  1.39722234,  0.        ,  0.97079403],
       [ 0.58468217,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.23601472,  0.389689  ,  0.        ],
       [ 0.        ,  0.5815627 ,  0.        ,  0.11855117]])

In [116]:
data[ data < 0 ] = 0

In [119]:
data[ names != 'Joe' ] = 7
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  0.54200134,  0.        ,  0.70987597],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.18384131,  0.        ,  0.        ,  0.        ],
       [ 0.2793218 ,  1.30167366,  0.        ,  0.19195833]])

In [120]:
arr = np.empty((8, 4))

In [121]:
for i in range(8):
    arr[i] = i

arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [122]:
arr[[4, 3, 0, 6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [123]:
arr[[ -3, -5, -7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [124]:
arr = np.arange( 32 ).reshape( ( 8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [126]:
arr[[1, 5, 7]][:, [0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30]])

In [127]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [128]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [129]:
arr = np.random.randn( 6, 3 )
arr

array([[ 0.00965833, -0.84008998, -0.29176654],
       [-0.94842769, -0.91698884,  0.08435008],
       [ 1.39275987,  0.05247766, -0.31061567],
       [ 0.40450182, -0.3486418 ,  1.73285468],
       [-0.41130876, -1.14109803, -0.89652973],
       [ 1.77981702, -1.08847167, -0.04380541]])

In [130]:
np.dot( arr.T, arr)

array([[ 6.33993365, -0.6742905 ,  0.47629683],
       [-0.6742905 ,  4.15780001,  0.61802536],
       [ 0.47629683,  0.61802536,  3.99719454]])

In [132]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [133]:
arr.transpose()

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [134]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [135]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [136]:
arr = np.arange(10)

In [137]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [139]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [140]:
x = np.random.randn(8)

In [141]:
y = np.random.randn(8)

In [142]:
x

array([ 1.1355102 , -0.06778429,  1.2145038 , -0.67748835, -1.35713781,
       -0.19576067,  1.50648087,  0.3587689 ])

In [143]:
y

array([ 0.26044182, -1.08445759,  0.46885912, -0.77762799,  1.11193592,
       -0.63010593, -0.44693614, -1.31940372])

In [144]:
np.maximum(x,y)

array([ 1.1355102 , -0.06778429,  1.2145038 , -0.67748835,  1.11193592,
       -0.19576067,  1.50648087,  0.3587689 ])

In [147]:
arr = np.random.randn(7) * 5
arr

array([-6.14330863,  1.05658883,  3.67098548,  1.69884181,  2.12787463,
       -6.3964006 ,  5.54389518])

In [148]:
remainder, whole_part = np.modf(arr)

In [149]:
remainder

array([-0.14330863,  0.05658883,  0.67098548,  0.69884181,  0.12787463,
       -0.3964006 ,  0.54389518])

In [150]:
whole_part

array([-6.,  1.,  3.,  1.,  2., -6.,  5.])

In [151]:
arr

array([-6.14330863,  1.05658883,  3.67098548,  1.69884181,  2.12787463,
       -6.3964006 ,  5.54389518])

In [152]:
np.sqrt(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([        nan,  1.02790507,  1.9159816 ,  1.30339626,  1.45872363,
               nan,  2.35454777])

In [153]:
np.sqrt(arr, arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([        nan,  1.02790507,  1.9159816 ,  1.30339626,  1.45872363,
               nan,  2.35454777])

In [154]:
arr

array([        nan,  1.02790507,  1.9159816 ,  1.30339626,  1.45872363,
               nan,  2.35454777])